name: Check

on:
  push:
    branches:
      - master
    tags:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  check:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Abusing os/version as placeholders for the subproject and the gradle tasks
        os: [01_java_gradle_groovy, 02_java_gradle_kotlin_dsl]
        version: [check, allTests, jacocoRootMerge, jacocoRootReport]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache global .gradle folder
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: global-gradle-${{ hashFiles('**/*.kt*') }}-${{ hashFiles('**/*.java') }}

      - name: Check with Gradle
        run: ./gradlew clean ${{ matrix.version }} --no-daemon
        working-directory: ${{ matrix.os }}
